import {type KanaData} from '@type/kana';

export const KANA_DATA: KanaData[] = [
  {kana: 'あ', reading: ['a']},
  {kana: 'い', reading: ['i']},
  {kana: 'う', reading: ['u']},
  {kana: 'え', reading: ['e']},
  {kana: 'お', reading: ['o']},
  {kana: 'か', reading: ['ka']},
  {kana: 'き', reading: ['ki']},
  {kana: 'く', reading: ['ku']},
  {kana: 'け', reading: ['ke']},
  {kana: 'こ', reading: ['ko']},
  {kana: 'さ', reading: ['sa']},
  {kana: 'し', reading: ['shi', 'si']},
  {kana: 'す', reading: ['su']},
  {kana: 'せ', reading: ['se']},
  {kana: 'そ', reading: ['so']},
  {kana: 'た', reading: ['ta']},
  {kana: 'ち', reading: ['ti', 'chi']},
  {kana: 'つ', reading: ['tu', 'tsu']},
  {kana: 'て', reading: ['te']},
  {kana: 'と', reading: ['to']},
  {kana: 'な', reading: ['na']},
  {kana: 'に', reading: ['ni']},
  {kana: 'ぬ', reading: ['nu']},
  {kana: 'ね', reading: ['ne']},
  {kana: 'の', reading: ['no']},
  {kana: 'は', reading: ['ha']},
  {kana: 'ひ', reading: ['hi']},
  {kana: 'ふ', reading: ['fu']},
  {kana: 'へ', reading: ['he']},
  {kana: 'ほ', reading: ['ho']},
  {kana: 'ま', reading: ['ma']},
  {kana: 'み', reading: ['mi']},
  {kana: 'む', reading: ['mu']},
  {kana: 'め', reading: ['me']},
  {kana: 'も', reading: ['mo']},
  {kana: 'や', reading: ['ya']},
  {kana: 'ゆ', reading: ['yu']},
  {kana: 'よ', reading: ['yo']},
  {kana: 'ら', reading: ['ra']},
  {kana: 'り', reading: ['ri']},
  {kana: 'る', reading: ['ru']},
  {kana: 'れ', reading: ['re']},
  {kana: 'ろ', reading: ['ro']},
  {kana: 'わ', reading: ['wa']},
  {kana: 'を', reading: ['wo']},

  {kana: 'が', reading: ['ga']},
  {kana: 'ぎ', reading: ['gi']},
  {kana: 'ぐ', reading: ['gu']},
  {kana: 'げ', reading: ['ge']},
  {kana: 'ご', reading: ['go']},
  {kana: 'ざ', reading: ['za']},
  {kana: 'じ', reading: ['ji']},
  {kana: 'ず', reading: ['zu']},
  {kana: 'ぜ', reading: ['ze']},
  {kana: 'ぞ', reading: ['zo']},
  {kana: 'だ', reading: ['da']},
  {kana: 'ぢ', reading: ['di']},
  {kana: 'づ', reading: ['du']},
  {kana: 'で', reading: ['de']},
  {kana: 'ど', reading: ['do']},
  {kana: 'ば', reading: ['ba']},
  {kana: 'び', reading: ['bi']},
  {kana: 'ぶ', reading: ['bu']},
  {kana: 'べ', reading: ['be']},
  {kana: 'ぼ', reading: ['bo']},

  {kana: 'ぱ', reading: ['pa']},
  {kana: 'ぴ', reading: ['pi']},
  {kana: 'ぷ', reading: ['pu']},
  {kana: 'ぺ', reading: ['pe']},
  {kana: 'ぽ', reading: ['po']},

  {kana: 'きゃ', reading: ['kya']},
  {kana: 'きゅ', reading: ['kyu']},
  {kana: 'きょ', reading: ['kyo']},
  {kana: 'ぎゃ', reading: ['gya']},
  {kana: 'ぎゅ', reading: ['gyu']},
  {kana: 'ぎょ', reading: ['gyo']},

  {kana: 'にゃ', reading: ['nya']},
  {kana: 'にゅ', reading: ['nyu']},
  {kana: 'にょ', reading: ['nyo']},

  {kana: 'ひゃ', reading: ['hya']},
  {kana: 'ひゅ', reading: ['hyu']},
  {kana: 'ひょ', reading: ['hyo']},
  {kana: 'びゃ', reading: ['bya']},
  {kana: 'びゅ', reading: ['byu']},
  {kana: 'びょ', reading: ['byo']},
  {kana: 'ぴゃ', reading: ['pya']},
  {kana: 'ぴゅ', reading: ['pyu']},
  {kana: 'ぴょ', reading: ['pyo']},

  {kana: 'みゃ', reading: ['mya']},
  {kana: 'みゅ', reading: ['myu']},
  {kana: 'みょ', reading: ['myo']},

  {kana: 'りゃ', reading: ['rya']},
  {kana: 'りゅ', reading: ['ryu']},
  {kana: 'りょ', reading: ['ryo']},

  {kana: 'じゃ', reading: ['ja']},
  {kana: 'じぇ', reading: ['je']},
  {kana: 'じゅ', reading: ['ju']},
  {kana: 'じょ', reading: ['jo']},

  {kana: 'ちゃ', reading: ['tya', 'cha']},
  {kana: 'ちぇ', reading: ['tye', 'che']},
  {kana: 'ちゅ', reading: ['tyu', 'chu']},
  {kana: 'ちょ', reading: ['tyo', 'cho']},

  {kana: 'しぇ', reading: ['she']},
  {kana: 'しょ', reading: ['sho']},
];